### ISSUE TITLE
docker cheat sheet

### ISSUE THREAD

**Issue by getElementsByName** [getElementsByName/tmp-doc#13]
## docker-compose
```yaml
version: '3'
services:
    airflow_local:
        container_name: airflow_local
        build:
            context: ${DOCKERFILE_DIR-.}
            dockerfile: ./Dockerfile
            # args:
            #     SAMPLE_BUILD_ARGS: "true"
        image: why/airflow-env:local
        # entrypoint: ["sh"]
        # command: ["-c", "make start"]
        # command: ["-c", "sleep 99999999"]
        ports:
        - "${HOST_PORT-8080}:8080"
        volumes:
        - airflow:/usr/local/airflow
        - $PWD/deploy/docker-images/airflow/standalone/airflow-home/airflow.cfg:/usr/local/airflow/airflow.cfg
        - airflow-dags:/usr/local/airflow/dags
        - hadoop-conf-data:/opt/cluster-conf
volumes:
    airflow:
    hadoop-conf-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/../hadoop/conf/production
    airflow-dags:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/dags
```
