### ISSUE TITLE
docker cheat sheet

### ISSUE THREAD

**Issue by getElementsByName** [getElementsByName/tmp-doc#16]
### docker-compose.yaml

```yaml
version: '3'
services:
    airflow_local:
        container_name: airflow_local
        build:
            context: ${DOCKERFILE_DIR-.}
            dockerfile: ./Dockerfile
        image: get-elements-by-name/airflow-standalone:local
        ports:
        - "${HOST_PORT-8080}:8080"
        volumes:
        - airflow:/usr/local/airflow
        - $PWD/deploy/docker-images/airflow/standalone/airflow-home/airflow.cfg:/usr/local/airflow/airflow.cfg
        - airflow-dags:/usr/local/airflow/dags
        - hadoop-conf-data:/opt/cluster-conf
volumes:
    airflow:
    hadoop-conf-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/../hadoop/conf/production
    airflow-dags:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/dags
```
