### ISSUE TITLE
helm

### ISSUE THREAD

**Issue by getElementsByName** [getElementsByName/tmp-doc#21]
```makefile
CHART_NAME=postgresql

ADDITIONAL_OPTIONS=
COMMON_VALUES=--values ./values/default.values.yaml --values ./values/secret.values.yaml --values ./values/app.values.yaml
PRODUCTION_VALUES_OPTIONS=--values ./values/production.values.yaml
COMMON_OPTIONS=$(COMMON_VALUES) $(CHART_NAME) $(ADDITIONAL_OPTIONS)

.PHONY: *

default:
	@echo DEPLOY postgresql CHART

helm-init-repo:
	helm repo add bitnami https://charts.bitnami.com/bitnami
	helm search postgresql

helm-dependency-update:
	helm dependency update


deploy.development:
	ncc helm upgrade --install $(COMMON_OPTIONS) $(VALUES_OPTIONS) ./

deploy.production:
	ncc helm upgrade --install $(COMMON_OPTIONS) $(PRODUCTION_VALUES_OPTIONS) $(VALUES_OPTIONS) ./

delete:
	ncc helm delete $(CHART_NAME) --purge
	kubectl delete pvc -l app.kubernetes.io/name=$(CHART_NAME)

expose:
	kubectl expose service/$(CHART_NAME) --name gateway-$(CHART_NAME) --type LoadBalancer
```

**Comment by getElementsByName** [comment]
### configMap
- values
```yaml
configGlobList:
    - assets/production/*
```

- configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name-prefix" . }}-config
data:
{{- range $.Values.configGlobList }}
{{ (tpl ($.Files.Glob . ).AsConfig $ ) | nindent 2 }}
{{- end }}
```
